[custom]
# ;This is an example external configuration file
# ;All possible customization settings are shown below

# ;Options for custom groups
# ;4654646465465
custom_proxy_group=ğŸ”° èŠ‚ç‚¹é€‰æ‹©`select`!!GROUPID=0
custom_proxy_group=â™»ï¸ è‡ªåŠ¨é€‰æ‹©`url-test`.*`http://www.gstatic.com/generate_204`300,5,100
custom_proxy_group=â“‚ï¸ å¾®è½¯æœåŠ¡`select`[]ğŸ¯ å…¨çƒç›´è¿`[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©
custom_proxy_group=ğŸ“² ç”µæŠ¥ä¿¡æ¯`select`[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©`[]ğŸ¯ å…¨çƒç›´è¿
custom_proxy_group=ğŸ è‹¹æœæœåŠ¡`select`[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©`[]ğŸ¯ å…¨çƒç›´è¿
custom_proxy_group=ğŸ¯ å…¨çƒç›´è¿`select`[]DIRECT
custom_proxy_group=ğŸ›‘ å…¨çƒæ‹¦æˆª`select`[]REJECT`[]DIRECT
custom_proxy_group=ğŸŸ æ¼ç½‘ä¹‹é±¼`select`[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©`[]ğŸ¯ å…¨çƒç›´è¿
custom_proxy_group=ğŸ”¯ AIæœåŠ¡`select`[]ğŸ”° èŠ‚ç‚¹é€‰æ‹©`[]DIRECT`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©

;Options for custom rulesets
enable_rule_generator=false
overwrite_original_rules=true

ruleset=â“‚ï¸ å¾®è½¯æœåŠ¡,https://cdn.jsdelivr.net/gh/17344config/clash-config@release/MSService-rules.txt
ruleset=ğŸ›‘ å…¨çƒæ‹¦æˆª,rules/NobyDa/Surge/AdRule.list
ruleset=ğŸ›‘ å…¨çƒæ‹¦æˆª,rules/DivineEngine/Surge/Ruleset/Guard/Hijacking.list
ruleset=â›”ï¸ å¹¿å‘Šæ‹¦æˆª,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
ruleset=;ğŸ¥ NETFLIX,rules/DivineEngine/Surge/Ruleset/StreamingMedia/Video/Netflix.list
ruleset=ğŸ“² ç”µæŠ¥ä¿¡æ¯,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
ruleset=ğŸ”° èŠ‚ç‚¹é€‰æ‹©,https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
ruleset=ğŸ è‹¹æœæœåŠ¡,rules/DivineEngine/Surge/Ruleset/Extra/Apple/Apple.list
ruleset=ğŸ¯ å…¨çƒç›´è¿,[]GEOIP,CN
ruleset=ğŸ¯ å…¨çƒç›´è¿,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
ruleset=ğŸ¯ å…¨çƒç›´è¿,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
ruleset=ğŸ¯ å…¨çƒç›´è¿,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
ruleset=ğŸ¯ å…¨çƒç›´è¿,https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
ruleset=ğŸŸ æ¼ç½‘ä¹‹é±¼,[]FINAL
ruleset=ğŸ”¯ AIæœåŠ¡,https://cdn.jsdelivr.net/gh/17344config/clash-config@release/AIService-rules.txt


;Options for custom base configuration file
clash_rule_base=base/forcerule.yml